dist: xenial
sudo: false
cache:
  bundler: true
language: ruby
services:
  - redis-server
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
branches:
  only:
    - master
install:
  - bundle install --without production development --deployment --jobs=3 --retry=3
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database helpline_test;' -U postgres
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
  - bundle exec rubocop
