sudo: false
cache:
  bundler: true
language: ruby
services:
  - redis-server
addons:
  postgresql: "10"
before_script:
  - psql -c 'create database helpline_test;'
branches:
  only:
    - master
install:
  - bundle install
script:
  - bundle exec rspec
  - bundle exec rubocop
